/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7-dev */

#ifndef PB_PB_SMARTKNOB_PB_H_INCLUDED
#define PB_PB_SMARTKNOB_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PB_KnobState {
    int32_t position;
    float force;
} PB_KnobState;

typedef struct _PB_TcpForce {
    float force;
} PB_TcpForce;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PB_KnobState_init_default           {0, 0}
#define PB_TcpForce_init_default            {0}
#define PB_KnobState_init_zero              {0, 0}
#define PB_TcpForce_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define PB_KnobState_position_tag           1
#define PB_KnobState_force_tag              2
#define PB_TcpForce_force_tag               1

/* Struct field encoding specification for nanopb */
#define PB_KnobState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    position,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    force,      2)
#define PB_KnobState_CALLBACK NULL
#define PB_KnobState_DEFAULT NULL

#define PB_TcpForce_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    force,      1)
#define PB_TcpForce_CALLBACK NULL
#define PB_TcpForce_DEFAULT NULL

extern const pb_msgdesc_t PB_KnobState_msg;
extern const pb_msgdesc_t PB_TcpForce_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PB_KnobState_fields &PB_KnobState_msg
#define PB_TcpForce_fields &PB_TcpForce_msg

/* Maximum encoded size of messages (where known) */
#define PB_KnobState_size                   16
#define PB_TcpForce_size                    5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
