/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "smartknob.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_KnobState, PB_KnobState, AUTO)
PB_BIND(PB_TcpForce, PB_TcpForce, AUTO) 